# Generated by Django 6.0 on 2026-01-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('account_balance', models.PositiveIntegerField(default=0, verbose_name='موجودی حساب')),
            ],
        ),
    ]
