# Generated by Django 6.0 on 2026-01-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='account_balance',
            field=models.CharField(default=0, verbose_name='موجودی حساب'),
        ),
    ]
