# Generated by Django 6.0 on 2026-01-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_dailyfood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='account_balance',
            field=models.IntegerField(default=0, verbose_name='موجودی حساب'),
        ),
    ]
