# Generated by Django 6.0.2 on 2026-05-04 08:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_student_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyfood',
            name='day',
            field=models.CharField(choices=[('sat', 'شنبه'), ('sun', 'یک شنبه'), ('mon', 'دوشنبه'), ('tue', 'سه شنبه'), ('wed', 'چهارشنبه'), ('thu', 'پنج شنبه'), ('fri', 'جمع')], max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='dailyfood',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
